#
# Module manifest for module 'Worker369.AWS.Readonly'
#
# Generated by: Sirius Chan
#
# Generated on: 10/2/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Worker369.AWS.Readonly.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'd4b00871-5d29-4c1e-96f5-ca7f9f29a34a'

# Author of this module
Author = 'Sirius Chan'

# Company or vendor of this module
CompanyName = 'Sirius Chan'

# Copyright statement for this module
Copyright = '(c) Sirius Chan. All rights reserved.'

# Description of the functionality provided by this module
# Description = ''

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.2'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module.
# This prerequisite is valid for the PowerShell Desktop edition only.
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module.
# This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    'Worker369.Utility',
    'AWS.Tools.Common',
    'AWS.Tools.CloudFormation',
    'AWS.Tools.CloudWatch',
    'AWS.Tools.CloudWatchLogs',
    'AWS.Tools.SecurityToken',
    'AWS.Tools.IdentityManagement',
    'AWS.Tools.EC2',
    'AWS.Tools.CloudFormation',
    'AWS.Tools.IdentityStore',
    'AWS.Tools.Lambda',
    'AWS.Tools.Organizations',
    'AWS.Tools.Route53',
    'AWS.Tools.S3',
    'AWS.Tools.SimpleEmailV2',
    'AWS.Tools.SimpleSystemsManagement',
    'AWS.Tools.SecurityToken',
    'AWS.Tools.SSOAdmin'
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry,
# use an empty array if there are no functions to export.
FunctionsToExport = @(

    # ---------------------------------------------------------------------------------------------------------------- #
    # Utilities
    # ---------------------------------------------------------------------------------------------------------------- #
    'Get-HintItem',                                                         # Consider to remove if released.
    'Get-QueryDefinition',                                                  # Consider to remove if released.
    'Get-ResourceString',                                                   # Consider to remove if released.
    #'New-TagSpecification',                                                 # Consider to remove if released.

    # ---------------------------------------------------------------------------------------------------------------- #
    # AWS Organization
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-OrgTree'                      # org_tree                          # Prints AWS Organization tree

    # ---------------------------------------------------------------------------------------------------------------- #
    # CloudFormation
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-Stack',                       # stack_show
    'Show-StackDrift',                  # stack_drift_show
    'Show-StackInstance',               # stack_instance_show
    'Show-StackResource',               # stack_resource_show
    'Show-IacScanBrief',                # iac_scan_brief
    'Show-IacScanDetail',               # iac_scan_detail

    # ---------------------------------------------------------------------------------------------------------------- #
    # CloudWatch Alarms
    # ---------------------------------------------------------------------------------------------------------------- #
    #'New-Ec2CpuAlarm',                  # alarm_ec2_cpu
    #'New-Ec2StatusAlarm',               # alarm_ec2_status

    # ---------------------------------------------------------------------------------------------------------------- #
    # EC2
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-Ec2',                         # ec2_show
    'Get-Ec2SystemLog',                 # ec2_console

    # ---------------------------------------------------------------------------------------------------------------- #
    # ENI
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-NetworkInterface',            # eni_show
    #'New-NetworkInterface',             # eni_add

    # ---------------------------------------------------------------------------------------------------------------- #
    # IAM
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-IamRole',                     # iam_role_show                 # Lists roles.
    'Show-IamRoleTrustPolicy',          # iam_role_trust_show           # Prints trust policy content
    'Find-IamPolicy',                   # iam_policy_find               # Searches policy ARNs
    'Read-IamPolicyDocument',           # iam_policy_read               # Lists policy statements in tablular column
    'Show-IamPolicyContent',            # iam_policy_cat                # Prints out the IAM policy content

    # ---------------------------------------------------------------------------------------------------------------- #
    # Identity Center
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-SsoAssignment',               # sso_assign_show               # Lists assignments to AWS accounts
    'Show-SsoUserPermission',           # sso_uperm_show                # Lists permissions assigned to SSO users

    # ---------------------------------------------------------------------------------------------------------------- #
    # Internet Gateway
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-InternetGateway',             # igw_show
    #'New-InternetGateway',              # igw_add
    #'Rename-InternetGateway',           # igw_rn
    #'Remove-InternetGateway',           # igw_rm
    #'Mount-InternetGateway',            # igw_mount                     # Attaches IGW to VPC
    #'Dismount-InternetGateway',         # igw_umount                    # Detaches IGW from VPC

    # ---------------------------------------------------------------------------------------------------------------- #
    # Lambda
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-Lambda',                      # func_show

    # ---------------------------------------------------------------------------------------------------------------- #
    # KMS
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-KmsKey',                      # kms_show

    # ---------------------------------------------------------------------------------------------------------------- #
    # Managed Prefix list
    # ---------------------------------------------------------------------------------------------------------------- #
    'Resolve-PrefixList',               # pl_resolve
    #'Write-PrefixList',                 # pl_write

    # ---------------------------------------------------------------------------------------------------------------- #
    # MFA
    # ---------------------------------------------------------------------------------------------------------------- #
    'Write-MfaProfile',                 # mfa

    # ---------------------------------------------------------------------------------------------------------------- #
    # Network ACL
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-NetworkAcl',                  # nacl_show
    #'New-NetworkAcl',                   # nacl_add
    #'Rename-NetworkAcl',                # nacl_rn
    #'Remove-NetworkAcl',                # nacl_rm

    # ---------------------------------------------------------------------------------------------------------------- #
    # Route 53
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-Route53Dns',                  # dns_show

    # ---------------------------------------------------------------------------------------------------------------- #
    # Route Table
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-RouteTable',                  # rt_show
    #'New-RouteTable',                   # rt_add
    #'Rename-RouteTable',                # rt_rn
    #'Remove-RouteTable',                # rt_rm
    #'New-RouteTableAssociation',        # rt_assoc_add
    #'Remove-RouteTableAssociation',     # rt_assoc_rm
    'Get-DefaultRouteTable',            # rt_default?                   # What is the shell's current route table
    'Set-DefaultRouteTable',            # rt_detault                    # Sets the shell's current route table
    'Clear-DefaultRouteTable',          # rt_default_clear              # Clears the shell's current route table
    'Show-Route',                       # route_show
    'Find-Route',                       # route_find
    #'Add-Route',                        # route_add
    #'Remove-Route',                     # route_rm

    # ---------------------------------------------------------------------------------------------------------------- #
    # S3
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-S3Folder',                    # s3_ls                         # Lists files
    'Show-S3FileContent',               # s3_cat                        # Prints file content
    'Show-S3FileVersion',               # s3_ver                        # Lists file versions
    'Get-S3File',                       # s3_get                        # Downloads file
    'Show-S3Bucket',                    # s3_show                       # Lists buckets
    'Show-S3Policy',                    # s3_policy_show                # Points bucket policy
    #'Clear-S3Bucket',                   # s3_clear                      # Empties bucket
    #'Enable-S3Versioning',              # s3_ver_en                     # Activates versioning
    #'Disable-S3Versioning',             # s3_ver_dis                    # Suspends versioning
    #'Enable-S3BucketKey',               # s3_bkey_en                    # Enable bucket key
    #'Disable-S3BucketKey',              # s3_bkey_dis                   # Disable bucket key
    #'Set-S3Encryption',                 # s3_encrypt                    # Sets default encryption
    #'Set-S3BlockedEncryption',          # s3_blkencrypt                 # Sets encryptions to block
    #'Clear-S3BlockedEncryption',        # s3_blkencrypt_clear           # Remove blocked encryptions

    # ---------------------------------------------------------------------------------------------------------------- #
    # Security Group
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-SecurityGroup',               # sg_show
    #'New-SecurityGroup',                # sg_add
    #'Copy-SecurityGroup',               # sg_cp                         # Copy all rules to another security group
    #'Clear-SecurityGroup',              # sg_clear                      # Remove all rules in a security group
    #'Rename-SecurityGroup',             # sg_rn
    #'Remove-SecurityGroup',             # sg_rm
    'Get-DefaultSecurityGroup',         # sg_default?                   # What is the shell's current security group
    'Set-DefaultSecurityGroup',         # sg_default                    # Sets the shell's current security group
    'Show-SecurityGroupRule',           # sgr_show

    # ---------------------------------------------------------------------------------------------------------------- #
    # SES
    # ---------------------------------------------------------------------------------------------------------------- #
    #'Send-SesMailMessage',              # ses_send

    # ---------------------------------------------------------------------------------------------------------------- #
    # SSM
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-Fleet',                       # fleet_show

    # ---------------------------------------------------------------------------------------------------------------- #
    # Subnet
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-Subnet',                      # subnet_show
    #'New-Subnet',                       # subnet_add
    #'Copy-Subnet',                      # subnet_cp                     # Clones a subnet with same attributes
    #'Rename-Subnet',                    # subnet_rn
    #'Remove-Subnet',                    # subnet_rm
    #'Add-SubnetIpv6Cidr',               # subnet_ipv6_add
    #'Remove-SubnetIpv6Cidr',            # subnet_ipv6_rm
    #'Enable-SubnetAAAARecord',          # subnet_aaaa_en
    #'Disable-SubnetAAAARecord',         # subnet_aaaa_dis
    #'Enable-SubnetARecord',             # subnet_a_en
    #'Disable-SubnetARecord',            # subnet_a_dis
    #'Enable-SubnetAutoAssignPublicIP',  # subnet_aip_en
    #'Disable-SubnetAutoAssignPublicIP', # subnet_aip_dis
    #'Enable-SubnetAutoAssignIPv6',      # subnet_aip6_en
    #'Disable-SubnetAutoAssignIPv6',     # subnet_aip6_dis
    #'Enable-SubnetDns64',               # subnet_dns64_en
    #'Disable-SubnetDns64',              # subnet_dns64_dis
    #'Set-SubnetHostnameType',           # subnet_host

    # ---------------------------------------------------------------------------------------------------------------- #
    # Transit Gateway
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-TransitGatewayRouteTable',    # tgw_rt_show
    'Show-TransitGatewayRoute',         # tgw_route_show

    # ---------------------------------------------------------------------------------------------------------------- #
    # VPC
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-Vpc',                         # vpc_show
    #'New-Vpc',                          # vpc_add
    #'Rename-Vpc',                       # vpc_rn
    #'Remove-Vpc',                       # vpc_rm
    #'Add-VpcIpv4Cidr',                  # vpc_ipv4_add
    #'Remove-VpcIpv4Cidr',               # vpc_ipv4_rm
    #'Add-VpcIpv6Cidr',                  # vpc_ipv6_add
    #'Remove-VpcIpv6Cidr',               # vpc_ipv6_rm
    'Show-VpcCidrMap'                   # vpc_cidrmap_show              # Lists VPC CIDRs utilisation
    #'Enable-VpcDnsResolution',          # vpc_dnsres_en
    #'Disable-VpcDnsResolution',         # vpc_dnsres_dis
    #'Enable-VpcDnsHostnames',           # vpc_dnshost_en
    #'Disable-VpcDnsHostnames',          # vpc_dnshost_dis
    #'Enable-VpcNauMetrics',             # vpc_nau_en
    #'Disable-VpcNauMetrics',            # vpc_nau_dis
    'Show-VpcBpaExclusion',             # vpc_bpa_excl_show
    #'New-VpcBpaExclusion',              # vpc_bpa_excl_add
    #'Edit-VpcBpaExclusion',             # vpc_bpa_excl_edit
    #'Remove-VpcBpaExclusion',           # vpc_bpa_excl_rm

    # ---------------------------------------------------------------------------------------------------------------- #
    # VPC Peering
    # ---------------------------------------------------------------------------------------------------------------- #
    'Show-VpcPeering'                  # pcx_show
    #'New-VpcPeering',                   # pcx_add
    #'Rename-VpcPeering',                # pcx_rn
    #'Remove-VpcPeering',                # pcx_rm
    #'Approve-VpcPeering',               # pcx_accept                    Accepts VPC peering requests
    #'Deny-VpcPeering',                  # pcx_reject                    Rejects VPC peering requests
    #'Enable-VpcPeeringDns',             # pcx_dns_en
    #'Disable-VpcPeeringDns'             # pcx_dns_dis
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry,
# use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry,
# use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess.
# This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}